# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91c6eda7c909300dd69b450779612bd9a5495e3dbea4c436a067ecb3d09a6bf9af368857532a2f15a2b598c9b476d11b9e287dc7edc0464a717f473069748b13

test:
  secret_key_base: 3741f581914ae420f284b4b0689edcaf34401be406719f51b0551223da1f36cfd58c9a1bb8bc430462252a7ea994897f5f8296cf029e031416514b9504590680

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
